Feature updates
sidsbrmnn/jwt_decode pull request #3
Opened 2020-12-21 21:16 UTC by VarunSAthreya

-   Features added:
    -   To check if the token is expired or not
    -   Get the expiry date
-   Added examples and test cases
-   Improved description and readme and changelog

2020-12-22 02:18 UTC, sidsbrmnn requested changes
Make the requested changes and I'll merge it

2020-12-22 02:18 UTC, sidsbrmnn commented on README.md
> +A easy dart package to decode jsonwebtokens, and to chack and give its expiry dates.
Rename jsonwebtokens as JSON Web Tokens and check spelling of "chack"

2020-12-22 02:18 UTC, sidsbrmnn commented on README.md
> +DateTime expiryDate = Jwt.getExpireyDate(token);
getExpiryDate spelling

2020-12-22 02:18 UTC, sidsbrmnn commented on README.md
> +To get the expiery date of the given token pass the token in the function `getExpireyDate()`.
Expiry date spelling

2020-12-22 02:18 UTC, sidsbrmnn commented on example/example.dart
> +  DateTime expiryDate = Jwt.getExpireyDate(token);
Spelling again

2020-12-22 02:18 UTC, sidsbrmnn commented on lib/jwt_decode.dart
> +  static DateTime getExpireyDate(String /*!*/ token) {
Spelling again

2020-12-22 02:18 UTC, sidsbrmnn commented on pubspec.yaml
> +description: A Dart package to decode jsonwebtokens, and to chack and give its expiry dates
Changes to description same as README

2020-12-22 02:18 UTC, sidsbrmnn commented on test/jwt_decode_test.dart
> +        Jwt.getExpireyDate(token), DateTime.parse('2021-12-22 01:46:13.000'));
Spelling of Expiry

2020-12-22 02:18 UTC, sidsbrmnn commented on test/jwt_decode_test.dart
> +    expect(() => Jwt.getExpireyDate(invalidToken), throwsFormatException);
Spelling of expiry

2020-12-22 11:13 UTC, VarunSAthreya commented
Resoled changes.

2020-12-23 04:50 UTC, sidsbrmnn requested changes

2020-12-23 04:50 UTC, sidsbrmnn commented on CHANGELOG.md
>  ## [0.1.1] - <Set Date>
One last change. Since you're adding new features, update the version to 0.2. Try and use semantic versioning every where.

2020-12-23 08:01 UTC, sidsbrmnn approved these changes
Perfect xD

2020-12-23 08:03 UTC, merged